version: '3.9'

services:
  web:
    build:  .
    container_name: ASR_backend
    volumes:
      - .:/app
    ports:
      - "8003:8001"
      - "8502:8502"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: mysql+pymysql://root:2002@db:3306/ASR
      BROKER_URL: redis://ASR_backend-redis-1:6379/0
      BACKEND_URL: redis://ASR_backend-redis-1:6379/0
      HF_TOKEN: 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
      CUDA_VISIBLE_DEVICES: 0
    networks:
      backend_net:
    deploy:
        resources:
          reservations:
            devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ["1"]



  db:
    image: mysql:8.0
    container_name: ASR_backend-db
    environment:
      MYSQL_ROOT_PASSWORD: 2002
      MYSQL_DATABASE: ASR
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p2002"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - backend_net

  redis:
    image: redis:7
    container_name: ASR_backend-redis-1
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - backend_net

volumes:
  mysql_data:
  redis_data:

networks:
  backend_net:
    driver: bridge
